modLoader = "javafml"
loaderVersion = "[21,)"
license = "MIT"

[[mods]]
modId = "leatherblocks"
version = "1.0.0"
displayName = "Leather Blocks"
description = '''Leder laesst sich zu Bloecken pressen - inklusive mehrerer Kompressionsstufen.'''

[[dependencies.leatherblocks]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leatherblocks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
