package de.cedric.leatherblocks;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Tiers, leather values and number formatting.
 *
 * Deliberately free of any Minecraft dependency, so the logic is testable
 * with a plain JDK (see tools/CoreTest.java).
 */
public final class LeatherTiers {

    public static final String MODID = "leatherblocks";
    public static final String LEATHER = "minecraft:leather";

    /**
     * Separator for chat output generated by the server.
     *
     * The item tooltip runs on the client and pulls its separator from the
     * language file. Chat messages, however, are built by the server, where
     * Language.getInstance() always resolves to en_us - there's no way to
     * reach the client's language from there. Hence this is fixed here, to
     * match the server audience.
     */
    public static final String SERVER_SEPARATOR = ".";

    /** Order = compression tier. Index 0 is crafted from 9x vanilla leather. */
    public static final String[] TIER_NAMES = {
            "leather_block",
            "compressed_leather_block",
            "double_compressed_leather_block",
            "triple_compressed_leather_block",
            "quadruple_compressed_leather_block",
            "quintuple_compressed_leather_block",
            "sextuple_compressed_leather_block",
            "septuple_compressed_leather_block",
            "octuple_compressed_leather_block",
            "nonuple_compressed_leather_block"
    };

    /** Item id -> leather equivalent. Also contains vanilla leather with value 1. */
    private static final Map<String, Long> VALUES;

    static {
        Map<String, Long> map = new LinkedHashMap<>();
        map.put(LEATHER, 1L);
        for (int tier = 0; tier < TIER_NAMES.length; tier++) {
            map.put(MODID + ":" + TIER_NAMES[tier], leatherIn(tier));
        }
        VALUES = Collections.unmodifiableMap(map);
    }

    /**
     * How much vanilla leather is contained in a block of this tier: 9^(tier+1).
     * Tier 9 is 3,486,784,401 - no longer fits in an int, hence long.
     */
    public static long leatherIn(int tier) {
        long total = 1L;
        for (int i = 0; i <= tier; i++) {
            total *= 9L;
        }
        return total;
    }

    public static boolean accepts(String itemId) {
        return VALUES.containsKey(itemId);
    }

    /** Leather equivalent of an item, 0 if the vault doesn't accept it. */
    public static long valueOf(String itemId) {
        return VALUES.getOrDefault(itemId, 0L);
    }

    /**
     * Addition that clamps at Long.MAX_VALUE instead of flipping negative.
     * Practically unreachable (2.6 billion blocks of the top tier), but an
     * overflowing high score would be a particularly dumb bug.
     */
    public static long addSaturating(long a, long b) {
        long sum = a + b;
        if (((a ^ sum) & (b ^ sum)) < 0) {
            return a > 0 ? Long.MAX_VALUE : Long.MIN_VALUE;
        }
        return sum;
    }

    /** Thousands grouping with a language-dependent separator. */
    public static String group(long value, String separator) {
        String digits = Long.toString(value);
        StringBuilder out = new StringBuilder(digits.length() + digits.length() / 3);
        for (int i = 0; i < digits.length(); i++) {
            if (i > 0 && (digits.length() - i) % 3 == 0) {
                out.append(separator);
            }
            out.append(digits.charAt(i));
        }
        return out.toString();
    }

    private LeatherTiers() {
    }
}
